tools:
  jdk:
    - 8
  maven:
    - 3.5.0

triggers:
  push: disabled
  pr: disabled

flows:
 default:
  - mvn install:install-file -Dfile=JMeter-InfluxDB-Writer-plugin-1.2.jar -DgroupId=com.sample -DartifactId=JMeter-InfluxDB-Writer-plugin -Dversion=1.2 -Dpackaging=jar
  - mvn clean verify -DRampUp=$RampUpPeriod -DThreadcount=$Number_of_Threads -DTotalRunTime=$Duration
pr:
   - call: default